{"actuators":[
  {"0":[
    {"name":"Power"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/0"},
    {"type":"set_value"},
    {"allowed_values":[
      "on",
      "off"
    ]}
  ]},
  {"1":[
    {"name":"TakePhoto"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/1"},
    {"type":"request"}
  ]},
  {"2":[
    {"name":"StartVideo"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/1"},
    {"type":"request"}
  ]},
  {"3":[
    {"name":"StopVideo"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/2"},
    {"type":"request"}
  ]},
  {"4":[
    {"name":"Mode"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/3"},
    {"type":"set_value"},
    {"allowed_values":[
      "video",
      "photo",
      "burst",
      "timelapse"
    ]}
  ]},
  {"5":[
    {"name":"VerticalOrientation"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/4"},
    {"type":"set_value"},
    {"allowed_values":[
      "normal",
      "inverted"
    ]}
  ]},
  {"6":[
    {"name":"VideoResolution"},
    {"info_url":"http://osdl.myspecies.info/node/11"},
    {"req_url":"a/5"},
    {"type":"set_value"},
    {"allowed_values":[
      "4k",
      "2.7k",
      "960"
    ]}
  ]}
]}
